### ISSUE TITLE
how can I find and open the .sqlite db. 

### ISSUE THREAD

**Issue by chenjie-cnooc** [alexblunck/MagicalRecord-Example-App#1]
I can run this demo. but I can't find the sqlite db file. I hope I can brow this sqlite file.

**Comment by alexblunck** [comment]
@chenjie-cnooc 

Hey, When app is run in the iOS Simulator the .sqlite backing CoreData will be at a path something like this:

/Users/[USERNAME]/Library/Application Support/iPhone Simulator/7.1/Applications/AA104DA4-647D-4E4F-924C-79A610D8D1B4/Library/Application Support/MagcalRecord Example

The longer character/numbers string will vary. Use an app like "SQLite Professional" to open the actual .sqlite file.
